import json
import os

notebook_content = {
    "cells": [
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 1. Setup environment and dependencies\n",
                "!pip install -q sentence-transformers qdrant-client pyarrow tqdm\n",
                "\n",
                "import torch\n",
                "print(f\"PyTorch Version: {torch.__version__}\")\n",
                "print(f\"CUDA Available: {torch.cuda.is_available()}\")\n",
                "if torch.cuda.is_available():\n",
                "    gpu_name = torch.cuda.get_device_name(0)\n",
                "    print(f\"Detected GPU: {gpu_name} -> Using CUDA GPU Acceleration!\")\n",
                "    DEVICE = \"cuda\"\n",
                "else:\n",
                "    print(\"Notice: No CUDA GPU detected, using multi-core CPU (8 threads).\")\n",
                "    DEVICE = \"cpu\"\n",
                "    torch.set_num_threads(8)\n",
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 2. Load Datasets: 318 National Laws + PhapDien (67,000+ Articles)\n",
                "import os, sys, time, re, urllib.request\n",
                "import pyarrow.parquet as pq\n",
                "\n",
                "articles = []\n",
                "CORPUS_DIR = '/tmp/data_corpus'\n",
                "os.makedirs(CORPUS_DIR, exist_ok=True)\n",
                "\n",
                "# 2.1 Load UTS_VLC (318 Laws)\n",
                "uts_found = False\n",
                "for cand in ['uts_vlc_2026_01.parquet', '/kaggle/working/uts_vlc_2026_01.parquet', os.path.join(os.getcwd(), 'uts_vlc_2026_01.parquet')]:\n",
                "    if os.path.exists(cand):\n",
                "        print(f'Loading local UTS_VLC from {cand}...')\n",
                "        table = pq.read_table(cand).to_pydict()\n",
                "        art_split_pattern = re.compile(r'(?=(?:^|\\n)(?:###?\\s*)?Điều\\s+\\d+[\\w\\.]*\\.?\\s*)', re.MULTILINE)\n",
                "        num_laws = len(table.get('id', []))\n",
                "        for i in range(num_laws):\n",
                "            law_id = str(table['id'][i])\n",
                "            law_title = str(table['title'][i]) if 'title' in table and table['title'][i] else ''\n",
                "            content = str(table['content'][i]) if 'content' in table and table['content'][i] else ''\n",
                "            domain = str(table['domain'][i]) if 'domain' in table and table['domain'][i] else 'Luật Quốc gia'\n",
                "            status = str(table['status'][i]) if 'status' in table and table['status'][i] else 'Còn hiệu lực'\n",
                "            code = str(table['code'][i]) if 'code' in table and table['code'][i] else ''\n",
                "            split_arts = art_split_pattern.split(content)\n",
                "            for idx, art in enumerate(split_arts[1:], 1):\n",
                "                art_clean = art.strip()\n",
                "                if not art_clean:\n",
                "                    continue\n",
                "                articles.append({\n",
                "                    'record_id': f'{law_id}-art-{idx}',\n",
                "                    'topic': 'Luật Quốc gia',\n",
                "                    'subject': domain,\n",
                "                    'document_title': law_title,\n",
                "                    'document_code': code,\n",
                "                    'article_title': art_clean.splitlines()[0][:140],\n",
                "                    'effective_status': status,\n",
                "                    'content_text': art_clean,\n",
                "                })\n",
                "        print(f'Loaded {len(articles):,} articles from 318 National Laws.')\n",
                "        uts_found = True\n",
                "        break\n",
                "\n",
                "# 2.2 Download & Load PhapDien (7 Parquet Shards)\n",
                "print('Downloading PhapDien shards...')\n",
                "HF_BASE = 'https://huggingface.co/datasets/tmquan/phapdien-moj-gov-vn/resolve/main'\n",
                "for i in range(7):\n",
                "    fname = f'articles-{i:05d}-of-00007.parquet'\n",
                "    lpath = os.path.join(CORPUS_DIR, fname)\n",
                "    if not os.path.exists(lpath):\n",
                "        urllib.request.urlretrieve(f'{HF_BASE}/{fname}', lpath)\n",
                "    t = pq.read_table(lpath).to_pydict()\n",
                "    for j in range(len(t['record_id'])):\n",
                "        articles.append({\n",
                "            'record_id': str(t['record_id'][j]),\n",
                "            'topic': str(t['topic_title_vi'][j] or 'Pháp điển'),\n",
                "            'subject': str(t['subject_title_vi'][j] or ''),\n",
                "            'document_title': str(t['source_note_text'][j] or 'Bộ Pháp điển Việt Nam'),\n",
                "            'document_code': '',\n",
                "            'article_title': str(t['article_title'][j] or ''),\n",
                "            'effective_status': 'Còn hiệu lực',\n",
                "            'content_text': str(t['content_text'][j] or ''),\n",
                "        })\n",
                "print(f'✅ Total Legal Articles to Index: {len(articles):,}')\n",
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 3. Load SOTA Embedding Model: darklethelong/vnlegal-lal\n",
                "from sentence_transformers import SentenceTransformer\n",
                "MODEL_NAME = 'darklethelong/vnlegal-lal'\n",
                "print(f'=== Loading Model: {MODEL_NAME} on {DEVICE} ===', flush=True)\n",
                "\n",
                "model = SentenceTransformer(MODEL_NAME, device=DEVICE)\n",
                "if DEVICE == 'cuda':\n",
                "    try:\n",
                "        model.half()\n",
                "        print('Enabled FP16 precision on CUDA.', flush=True)\n",
                "    except Exception as e:\n",
                "        print(f'Notice on FP16: {e}', flush=True)\n",
                "\n",
                "VECTOR_DIM = 1024\n",
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 4. Initialize Local Qdrant Database\n",
                "import os, time\n",
                "from qdrant_client import QdrantClient\n",
                "from qdrant_client.models import VectorParams, Distance, HnswConfigDiff, PayloadSchemaType, PointStruct\n",
                "\n",
                "OUTPUT_DIR = '/tmp/qdrant_db'\n",
                "os.makedirs(OUTPUT_DIR, exist_ok=True)\n",
                "\n",
                "client = QdrantClient(path=OUTPUT_DIR)\n",
                "COLLECTION_NAME = 'vietnam_legal_collection_v1'\n",
                "\n",
                "client.create_collection(\n",
                "    collection_name=COLLECTION_NAME,\n",
                "    vectors_config=VectorParams(size=VECTOR_DIM, distance=Distance.COSINE),\n",
                "    hnsw_config=HnswConfigDiff(m=16, ef_construct=128, full_scan_threshold=10000),\n",
                ")\n",
                "\n",
                "for field in ['topic', 'subject', 'effective_status', 'document_title']:\n",
                "    try:\n",
                "        client.create_payload_index(collection_name=COLLECTION_NAME, field_name=field, field_schema=PayloadSchemaType.KEYWORD)\n",
                "    except Exception as e:\n",
                "        pass\n",
                "\n",
                "print(f'✅ Qdrant Collection {COLLECTION_NAME} initialized.', flush=True)\n",
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 5. Batch Encoding with Live Progress\n",
                "BATCH_SIZE = 64 if DEVICE == 'cuda' else 32\n",
                "texts_to_embed = [\n",
                "    f\"Văn bản: {a['document_title']}\\nChủ đề: {a['topic']} - {a['subject']}\\nĐiều: {a['article_title']}\\nNội dung: {a['content_text'][:3500]}\"\n",
                "    for a in articles\n",
                "]\n",
                "\n",
                "total_records = len(articles)\n",
                "started_at = time.time()\n",
                "print(f'=== Starting Batch Encoding of {total_records:,} items (Batch Size: {BATCH_SIZE}) ===', flush=True)\n",
                "\n",
                "for batch_num, idx in enumerate(range(0, total_records, BATCH_SIZE), 1):\n",
                "    batch_texts = texts_to_embed[idx : idx + BATCH_SIZE]\n",
                "    batch_articles = articles[idx : idx + BATCH_SIZE]\n",
                "    \n",
                "    with torch.no_grad():\n",
                "        embeddings = model.encode(\n",
                "            batch_texts,\n",
                "            batch_size=BATCH_SIZE,\n",
                "            show_progress_bar=False,\n",
                "            normalize_embeddings=True,\n",
                "        )\n",
                "    \n",
                "    points = [\n",
                "        PointStruct(\n",
                "            id=idx + i + 1,\n",
                "            vector=embeddings[i].tolist(),\n",
                "            payload={\n",
                "                'record_id': item['record_id'],\n",
                "                'topic': item['topic'],\n",
                "                'subject': item['subject'],\n",
                "                'document_title': item['document_title'],\n",
                "                'document_code': item['document_code'],\n",
                "                'article_title': item['article_title'],\n",
                "                'effective_status': item['effective_status'],\n",
                "                'source': item['document_title'],\n",
                "                'text': item['content_text'][:2000],\n",
                "            }\n",
                "        )\n",
                "        for i, item in enumerate(batch_articles)\n",
                "    ]\n",
                "    \n",
                "    client.upsert(collection_name=COLLECTION_NAME, points=points)\n",
                "    \n",
                "    current_count = min(idx + len(batch_articles), total_records)\n",
                "    elapsed = time.time() - started_at\n",
                "    speed = current_count / max(elapsed, 0.1)\n",
                "    remaining = (total_records - current_count) / max(speed, 0.1)\n",
                "    pct = (current_count / total_records) * 100\n",
                "    print(f'⚡ [{current_count:,}/{total_records:,}] ({pct:.1f}%) | Speed: {speed:.1f} vec/s | Elapsed: {elapsed:.0f}s | ETA: {remaining:.0f}s', flush=True)\n",
                "\n",
                "duration = time.time() - started_at\n",
                "print(f'🎉 Completed indexing {total_records:,} vectors in {duration:.1f}s (Avg speed: {total_records/duration:.1f} vec/s)', flush=True)\n",
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# 6. Compress into Artifact\n",
                "import os, tarfile\n",
                "artifact_name = '/kaggle/working/qdrant_vnlegal_lal.tar.gz'\n",
                "print(f'Compressing {OUTPUT_DIR} into {artifact_name}...', flush=True)\n",
                "with tarfile.open(artifact_name, 'w:gz') as tar:\n",
                "    tar.add(OUTPUT_DIR, arcname='qdrant_db')\n",
                "size_mb = os.path.getsize(artifact_name) / (1024 * 1024)\n",
                "print(f'✅ Artifact created: {artifact_name} ({size_mb:.1f} MB)', flush=True)\n",
            ]
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "kaggle": {
            "accelerator": "nvidiaTeslaT4",
            "dataSources": [],
            "isGpuEnabled": True,
            "isInternetEnabled": True,
            "language": "python"
        },
        "language_info": {
            "name": "python"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

with open(r"c:\Users\trant\Documents\Interview\vietnam-legal-agent\kaggle_indexer\build_index_kaggle.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook_content, f, indent=2)
print("build_index_kaggle.ipynb created successfully.")
